/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sunjing' at '10/20/16 8:27 AM' with Gradle 2.10
 *
 * @author sunjing, @date 10/20/16 8:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
